### ISSUE TITLE
wasm?

### ISSUE THREAD

**Issue by jhpratt** [swc-project/swc#106]
Could this potentially be compiled to WebAssembly? This would allow full interop with the existing Babel packages, and would truly thrust this project into the spotlight.

**Comment by dennythecoder** [comment]
You may want to check out https://github.com/swc-project/swc/issues/87

**Comment by anurbol** [comment]
@kdy1 Continuing https://github.com/swc-project/swc/issues/87#issuecomment-563009276... So what are those `cfg`s to build a wasm binary? I've tried to build only the Parser for WASM and got this [error](https://github.com/rust-lang/rust/issues/67170) I am not sure if it relates to SWC or to Rust. Do you have any clues?

**Comment by kdy1** [comment]
@anurbol 

> So what are those cfgs to build a wasm binary? 
`#[cfg]` should be placed on some structs in swc_common. Other codes do not use os-specific features.


> got this error I am not sure if it relates to SWC or to Rust. Do you have any clues?
I think it's rustc's bug related to wasm target. I'm not sure about the way to fix it.

**Comment by anurbol** [comment]
@kdy1 Hey, I've managed to compile the Parser (nothing more) with `--target wasm32-unknown-unknown`! It turns out that dependency renaming is [broken](https://github.com/rust-lang/rust/issues/64450) for the Wasm target. Therefore I did this...
In ecmascript\parser\Cargo.toml 
Changed this:
```
ast = { package = "swc_ecma_ast", version = "0.10.0", path ="../ast" }
parser_macros = { package = "swc_ecma_parser_macros", version = "0.4", path ="./macros" }
```
...to this...
```
swc_ecma_ast = { version = "0.10.0", path ="../ast" }
swc_ecma_parser_macros = { package = "swc_ecma_parser_macros", version = "0.4", path ="./macros" }
```
...and minor things, including replacements throughout the `swc_ecma_parser` crate.

Is it OK? Are the new names OK? Can I make a pull request?

BTW this project is incredible, I am your fan, are you even a human? Because humans can't do such amount of work 😄

**Comment by kdy1** [comment]
@anurbol I'll be happy with a such PR. Thank you for the interest on swc!

**Comment by anurbol** [comment]
Hey people, SWC Parser can be built for Wasm! If someone needs, I think, you could make the whole SWC project Wasm-compatible easy enough. So when you build for Wasm you'd likely see the `inconsistent resolution for an import` error. To fix that, you should get rid of dependency renaming in Cargo.toml files across the whole SWC project. Example is [here](https://github.com/swc-project/swc/issues/106#issuecomment-564028370)

**Comment by 3cp** [comment]
I would love to see a swc wasm release. Even a separated npm package name is fine.

I am using babel and tsc in both nodejs and browser env. But they are both too slow and consume too much memory for my taste.

Very interested on swc!

**Comment by alubbe** [comment]
Came here to further express my interest in a wasm release. If the performance is roughly similar, then I believe going wasm would be a tremendous boost to the reach and usage of swc because it suddenly works on every modern browser, every modern version of node and on every operating system that v8 supports - without needing to configure a build system or pre-building binaries. 

Personally, I think a great way to continue the discussion would be for @anurbol to contribute his work as a PR and then discuss the feasibility of the changes and measure the performance impact. Happy to help out!

**Comment by anurbol** [comment]
@alubbe I have already contributed a very simple [PR](https://github.com/swc-project/swc/pull/495) that restored Wasm support for SWC Parser. Yes, SWC is WASM-ready, mostly, just some configuration files should be [fixed](https://github.com/swc-project/swc/issues/106#issuecomment-564411519). Regarding performance impact, in my case WASM was 2 to 3 times slower than native binary, but still this is like x50 times faster than JS.

**Comment by alubbe** [comment]
Ah awesome, I hadn't seen that! So the next step would be a for a second PR to rename the dependencies and then possibly a third PR to introduce wasm building to the CI process, so that it doesn't get broken going forward?

**Comment by anurbol** [comment]
@alubbe Yep, seems so! Currently I don't have time for this, but this is simple enough so if you have time you could try.

**Comment by kdy1** [comment]
I've implemented transformSync and transformFileSync. It seems like wasm is 3 ~ 4 times slower than native binary.

Please tell me if is it ok. If it's ok, I'll implement other methods for wasm and make it fallback for the swc.

I uploaded the benchmark result at:: https://github.com/swc-project/swc/pull/691

**Comment by alubbe** [comment]
Out of interest, could you include babel or other pure JS alternatives in your benchmark?

**Comment by kdy1** [comment]
@alubbe I included babel, but I didn't benchmark tsc because it does much more work than swc. It will be very slow, but it's expected as it does much more work.
For the same reason, I didn't include sucrase because it cannot compile to es3 / es2015.

**Comment by alubbe** [comment]
Ah you're right, it's at the end of the benchmark. So for es2015, the WASM version is around 4-5 times faster and the native one is around 9 times faster than babel, right?

**Comment by kdy1** [comment]
@alubbe Oh. I made a mistake. es2015 in swc is equivalent with es5 because there's no es2015 -> es5 pass.

So the native version is 17 times faster than babel.

**Comment by kdy1** [comment]
#691 Is merged. Closing. Please comment or file a new issue if it's not enough.
