### ISSUE TITLE
TypeScript type imports are only stripped when they are used as a type at least once

### ISSUE THREAD

**Issue by lucacasonato** [swc-project/swc#1065]
**Describe the bug**

TypeScript type imports are only stripped when they are used as a type at least once, even if they are not used as a value.

**Input code**

Working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";

interface MySecondaryType extends MyType {
  
}
```

Not working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";
```

Also not working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";
export type { MyType };
```

**Expected behavior**
I expect that `import { MyType } from "./test2.ts";` is stripped away in both examples.

**Comment by kdy1** [comment]
This is intended for multiple reason.

 1. At the time of implementing it, type-only imports without `import type` are only stripped out if it's used as type.

[ts 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)  introduced type-only imports, because the problem I wrote above.

 2. `swc` works on file-by-file basis, so it cannot know if it's a type-only.



Even though, I'm considering two options.

 1. Implement emit-only tsc which also handles some special stuffs like const enum within **swc_bundler**, as it already works by loading multiple file.

 2. Add config to allow user select which behavior should be used.


Lastly, closing in favor of https://github.com/swc-project/swc/pull/1060

**Comment by nayeemrmn** [comment]
@kdy1 Not sure I understand. It doesn't need to know if it's type in the imported module, because if it's not used at all in the importing module then it can be stripped either way. This is the behaviour of tsc. It's not intended. TS 3.8 type only imports are to address the re-export case.

**Comment by kdy1** [comment]
I confused the behavior of babel with one of tsc.

**Comment by lucacasonato** [comment]
@kdy1 Also this is not being stripped correctly:

```ts
import { MyType } from "./test2.ts";
export type { MyType };
```

Should I open a new bug for this?

**Comment by kdy1** [comment]
I'll just reopen it.
