### ISSUE TITLE
How do you actually use a custom plugin?

### ISSUE THREAD

**Issue by andrew-knack** [swc-project/swc#1253]
In the documentation it [shows how to write a plugin](https://swc.rs/docs/usage-plugin) and how to use it programatically but fails to mention how to configuring it by using a `.swcrc` file.  

I've looked through all the documentation and a decent amount of the source code and the only mention I can see is [this commented out option on the cli](https://github.com/swc-project/cli/blob/master/src/spack/options.ts#L96).

I can't imagine that's the intended case because how would you use a plugin with the `cli`, `@swc/jest`, `swc-loader` or `@swc/register`?

**Comment by kdy1** [comment]
Such api is planned and now it's possible, but I'm too busy these days.
Next week is final exam, so I will have lots of time after it.

I'll try implementing this.

**Comment by Kaandriambelo** [comment]
Hello,

I'm currently working on a project using babel.
We've seen pretty good reviews about swc so we would to test it out.
Since swc does not support typescript path yet, i'm trying to mend this by creating a custom plugin to resolve the path in tsconfig file.
My question is, how do i actually use this plugin i created ?
I saw plugins examples in the documentation but not how to actually use them.

Which file should i actually modify to tell swc to use this plugin i created ?
What i would like to do is: on top of swc base feature, i would like to run this plugin every time a file is changed (e.g. on watch mode) to resolve my path.
Any notes regarding the plugin usage would be very much appreciated.

Kind regards,
Kanto

**Comment by chin2km** [comment]
Is there a way to configure a custom AST plugin in `.swcrc` or `swc-loader` options? 
I couldn't find one in the documentations.
@kdy1

**Comment by kdy1** [comment]
No, you can specify only rust-based plugins in `.swcrc` or `swc-loader` options.

**Comment by chin2km** [comment]
You mean the plugin itself should be written in rust?
My use-case is I currently have a babel transform [here](https://astexplorer.net/#/gist/0a7dd5cb86918be46bb2430759b92bd4/f9decdf348862ad4c001e4aa67827be0e86f0b60)
Whats the best way to migrate that transform to something `swc` can use?

Thanks for the quick reply btw :) @kdy1

**Comment by kdy1** [comment]
> You mean the plugin itself should be written in rust?

Yes.

> Whats the best way to migrate that transform to something swc can use?

Currently there's no good way. Rust-based plugin system need some more work.

**Comment by hugufc** [comment]
> 

On [#2113](https://github.com/swc-project/swc/discussions/2113#discussioncomment-2177592) discussion was pointed that a solution have been released as experimental.

> To load plugins, you may use swcrc's jsc.experimental configs:
> 
> ```
> {
>   jsc: {
>     ...
>    experimental: {
>      ...
>      cache_root: String // optional, specify where swc will create wasm bytecode cache
>     // list of plugins. If `pluginname` is resolvable to npm package, it'll try to load from installed npm packages.
>     // or it can be an absolute path to the .wasm binary
>      plugins: [ ['pluginname', pluginOptions: Record<string, any>] ] 
>    }
> }
> ```

**Comment by kwonoj** [comment]
This should be answered via https://github.com/swc-project/swc/discussions/3540
