### ISSUE TITLE
How to use a custom plugin in the CLI arguments?

### ISSUE THREAD

**Issue by mazipan** [swc-project/swc#1384]
In the [plugins](https://swc.rs/docs/usage-plugin#using-multiple-plugins) section, already state that we can create a custom plugin to extend the SWC ability.

But the Docs still not tell us how to integrate that custom plugin into our current pipeline if we use `@swc/cli`.

Can someone help me to understand how to pass plugins in the CLI?
Or if not possible, are there any alternative to use this plugin along with our current swc configurations?

**Comment by kdy1** [comment]
Babel-like plugin api is planned, but currently, the only way to use plugins is via core api.

(Although adding plugin support to cli would not be very hard, I'm too busy)

**Comment by Kaandriambelo** [comment]
Hello,

I'm currently working on a project using babel. 
We've seen pretty good reviews about swc so we would to test it out.
Since swc does not support typescript path yet, i'm trying to mend this by creating a custom plugin to resolve the path in tsconfig file.
My question is, how do i actually use this plugin i created ?
I saw plugins examples in the documentation but not how to actually use them.

Which file should i actually modify to tell swc to use this plugin i created ?
What i would like to do is: on top of swc base feature, i would like to run this plugin every time a file is changed (e.g. on watch mode) to resolve my path.
Any notes regarding the plugin usage would be very much appreciated.

Kind regards,
Kanto

**Comment by kwonoj** [comment]
Closing as outdated, primary way to use plugin is using configuration, and swcx cli partially 
supports cli input may updated in further.
