### ISSUE TITLE
Function name unnecessarily (and possibly wrongly) renamed

### ISSUE THREAD

**Issue by pbadenski** [swc-project/swc#1600]
**Describe the bug**

```
const x = function a() {};

const y = function a() {};
```

After running `swc test.ts`:
```
"use strict";
const x = function a() {
};
const y = function a1() {
};
```

Wondering whether SWC should preserve second function name as `a` - as intended in the original code? (Babel does)
In fact I'm not quite sure why SWC is renaming second function name at all.

**Config**

```json
{
  "env": {
    "targets": {
      "node": "15.10"
    }
  },
  "jsc": {
    "target": "es2019",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Version**
```
@swc/cli: 0.1.39
@swc/core: 1.2.54
```

**Comment by devongovett** [comment]
You probably shouldn't rely on the function name for your code to work correctly. Most minifiers rename them anyway.

**Comment by jdb8** [comment]
Ran into this myself when wondering why Enzyme tests started failing: turns out that Babel (seemingly as part of `preset-env` - [repl link](https://babeljs.io/repl/#?browsers=defaults&build=&builtIns=usage&corejs=3.6&spec=false&loose=true&code_lz=G4QwTgBAYg9jEF4IAoAOYaoM4EpED4IBvAXwG4g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.15.1&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.14.5%2C%40babel%2Fplugin-transform-react-display-name%407.15.0&assumptions=%7B%7D)) will take code like:

```js
var Foo = (props) => {};
```

and output

```js
var Foo = function Foo(props) {};
```

with a named function. If you then pass this through `swc`, it will rename the function to `Foo1`:

```js
var Foo = function Foo1(props) {};
```

This causes Enzyme tests to fail because React `displayName`s, when not set, are based on the function name here: so a function that Babel was reliably producing as `Foo` would now be seen in the React dom as `Foo1`. Arguably code shouldn't be relying on this behaviour, but it was surprising and is making it tricky to migrate from Babel to `swc` seamlessly.

Updating code to instead just declare `function Foo` instead of assigning to an anonymous arrow function works to "fix" it, but it means updating lots of packages which may be implicitly relying on the way Babel transpiles things and so are not setting `displayName` explicitly.

FWIW this happens without any config passed to `swc`. Weirdly, this behaviour doesn't seem to repro in the online `swc` repl (https://swc.rs/repl) - not sure if there's an older or newer version running there which differs from my local version (1.2.74).

**Comment by RyannGalea** [comment]
Was this added to v1.2.79 ?

**Comment by kdy1** [comment]
Yes, because this requires some work. I decided to postpone this when I'm releasing `v1.2.78`

**Comment by RyannGalea** [comment]
Hi @kdy1 ,

Trying again using this config but no changes are happening to the output, is there another setting here that is colliding with it?

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es5",
    "loose": true,
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "experimental": {
      "optimizeHygiene": true
    }
  },
  "env": {
    "targets": {
      "node": "14"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
} 
```

**Comment by RyannGalea** [comment]
@kdy1 

After updating and trying again, it does what I was originally asking but not adding the '1' to all my classes but it seems like something else is happening with decorators. as I get this error when I call the server.

```
[GraphQLError [Object]: Service with "<UNKNOWN_IDENTIFIER>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.] {
```

```
@Service()
@Resolver()
export class LoggedUserQuery {

  constructor(private readonly us: UserService){ }

  @Query(returns => User)
  @CatchAll('Logged User Error')
  async loggedUser(
    @Ctx() { req },
    @CtxUser() { _id }
  ): Promise<User | null> {
    if (!_id) return null
    const user = await this.us.findOne({_id}, ['business'])
    req.session.user = user
    return user
  }
  
} 


```

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es5",
    "loose": true,
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "experimental": {
      "optimizeHygiene": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
} 
```
