### ISSUE TITLE
Import statements are hoisted when target is CommonJs

### ISSUE THREAD

**Issue by petkaantonov** [swc-project/swc#1686]
**Describe the bug**

Import statements are hoisted when target is CommonJS:

```
import A from "a;
console.log(1);
import B from "a";
```

Becomes

```
require(...);
require(...);
console.log(1);
```

This is incorrect, require calls are normal functions and should have preserved order. Imports should only be hoisted when they are actual es6 imports. This is incompatible with tsc and probably others, tsc keeps the order as expected when output module is commonjs.

**Additional context**

It was fixed but then reverted in https://github.com/swc-project/swc/issues/1457

**Comment by mischnic** [comment]
With native esm (in Node or in browsers), the following prints "a, b, index"

```js
// index.js
import "./a.js";
console.log("index");
import "./b.js";

// a.js
console.log("a");

// b.js
console.log("b");
```

And I'd argue that transpiling the code to CJS shouldn't change the behaviour of the code

**Comment by petkaantonov** [comment]
- It is incompatible with tsc
- It sucks for commonjs users, remember we are forced to use import not because it is better syntax but because typescript types dont work with require
- If you are able to use esm, why compile code to cjs? and why expect the behavior be the same? They are incompatible module systems.

**Comment by mischnic** [comment]
From my perspective, the real problem is that [tsc](https://www.typescriptlang.org/play?module=1&ssl=1&ssc=1&pln=3&pc=12#code/JYWwDg9gTgLgBAIgIYINwCgDGEB2BnCAGwFMA6QiAcwAoBGASg1ElkQCM0g) and [Babel](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAIgIYINwCgDGEB2BnCAGwFMA6QiAcwAoBGASg1ElkQCM0g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.14.1&externalPlugins=)/the spec don't agree

I guess swc has to choose a side here.

**Comment by kdy1** [comment]
This feature is useful for using some of node.js modules, which expect execution order of common js modules.
So I think this behavior should be allowed, but only with a bad-named flag, just like `dangerouslySetInnerHTML`.
I'll think more about the name of the flag.

**Comment by petkaantonov** [comment]
Some suggestions: disableImportHoisting, noImportHoist

**Comment by devongovett** [comment]
Isn't this exactly what the jest mock transform allows already? Do you have a different use case for this? IMO deviating from the spec behavior is a bad idea. TSC is simply wrong.

**Comment by kdy1** [comment]
I missed that users can use `require`.
Thanks, @devongovett !

I think users should use `require` if the execution order of `require` is required.

**Comment by devongovett** [comment]
Also fwiw TSC is planning on changing this. https://github.com/microsoft/TypeScript/pull/39764

**Comment by lagnat** [comment]
> Also fwiw TSC is planning on changing this. [microsoft/TypeScript#39764](https://github.com/microsoft/TypeScript/pull/39764)

Apparently not.  The PR was closed and the bug is marked won't-fix.

**Comment by kdy1** [comment]
@lagnat Please see https://github.com/swc-project/swc/issues/5205

**Comment by lagnat** [comment]
We could argue if it's a tsc bug or not but we won't convince each other.  What is more at issue is that some projects that use tsc cannot safely switch to swc without re-writes.  You could add a compatibility flag to get more projects using swc but it seems that the swc teams is not interested in that and I'm here to voice my opinion that I find it unfortunate.

**Comment by magic-akari** [comment]
@lagnat evanw's explanation is the best answer.

> The conversion from ESM to CommonJS done by esbuild attempts to preserve the behavior of the original code as much as possible. What you are observing happens because in ESM, all imports are essentially "hoisted" to the top of the file since all dependencies of a given file must be evaluated before any code in that file is evaluated. This is just how the JavaScript language works. More information: https://github.com/evanw/esbuild/issues/1395#issuecomment-869026051.
>
> The code you wrote happens to work due to a defect in the TypeScript compiler: https://github.com/microsoft/TypeScript/issues/16166#issuecomment-318782098. Writing such code is risky because your code will break as soon as it's run in a real ESM environment (such as esbuild, or node's ESM mode, or in a browser).

_Originally posted by @evanw in https://github.com/evanw/esbuild/issues/1444#issuecomment-881754338_

**Comment by lagnat** [comment]
It's not a defect because Microsoft closed the bug report as won't-fix and didn't take the PR.  Microsoft gets to decide how tsc works and this is what they've decided.  I get that you don't agree with the decision and I understand why.. in fact I totally agree with you, but tsc works the way it works and I don't see it changing. I fully acknowledge that the authors of swc can do whatever they want too but it's a strange hill to die on because it hinders a wider adoption of swc.  Adding a config option such as `emulateBuggyTscAndDontHoist` makes your position clear and gets more code on swc.  I don't use esm at the moment and I acknowledge that I'll be forced to deal with this issue when that time comes.

**Comment by kdy1** [comment]
Please use discussion thread instead
