### ISSUE TITLE
Class Private Fields/Accessors/Methods must not be re-initialized on instance

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1743]
**Describe the bug**

(Example copied from https://github.com/babel/babel/issues/13299)

**Input code**

(Run with Node)

```js
const assert = require("assert");

class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;
class Derived extends Base {
  #foo = ++counter;
  static get(obj) {
    return obj.#foo;
  }
}

const foo = {};
new Derived(foo);
assert.equal(Derived.get(foo), 1);

// This should throw an error, private fields must not be re-initialized
// on an object that already contains the field.
assert.throws(() => {
  new Derived(foo);
});
// ^ That should have thrown, but it doesn't.

// Must not re-initialize the field
assert.equal(Derived.get(foo), 1);
// But the counter is incremented (the initializer runs, but the field
// should not re-add)
assert.equal(counter, 2);
```

**Config**

**Current behavior**
The assertions fail after transpiling

**Expected behavior**
Behaviour doesn't change

**Version**
The version of @swc/core: 1.2.58

**Comment by kdy1** [comment]
I found the fix for this, but to make output small, a new helper is required. (`_initClassPrivateProp `maybe)
As removing a helper is breaking change, I will think about this issue bit more.


Oh, I found that the babel issue has comments regarding the output size.
As this patch is not necessary for 99.99% of apps, I'll find a way to reduce output size regression.

**Comment by mischnic** [comment]
Sure, I didn't actually run into this myself, I just found this on the Babel bugtracker
