### ISSUE TITLE
File System Emulation

### ISSUE THREAD

**Issue by tryhardest** [swc-project/swc#1833]
Noticed the multiple bundler docs page has nothing on it.

![image](https://user-images.githubusercontent.com/53920284/122517158-8bbea980-cfc4-11eb-990a-12b1500dd812.png)

That said, noticed this in the ES build repo and this is exactly what we need (File system emulation) but not looking to get into Webpack, Parcel or Rollup atm. This looks great but would it fit the scope?  Having the top-level directory being bundled and all files inside it (or at least, the subset of the top-level directory that you intend to be accessible at run-time) into the bundle couldn't be described any better and is exactly what I am looking for. Thanks.

https://github.com/evanw/esbuild/issues/1375

**Comment by kdy1** [comment]
I think passing multiple files as enrties to the bundler would work for most of the bundlers.
Why is fs emulation required?

**Comment by CodeWithOz** [comment]
The particular use case is one where the code uses node's `fs.open` method. The file being opened is not an entry point for the app, it's a file that's needed by a dependency of the app. Please have a look at the exact code I'm referring to [here](https://github.com/geoip-lite/node-geoip/blob/78f4c7f0f3b6fa673035b3cb48c3a2a95be9fb0a/lib/geoip.js#L276). I'm using that package and ESbuild fails to bundle because of that line of code.

**Comment by kdy1** [comment]
I'll happily accept a PR and maintain it, but I think I'll not implement this by myself because I have lots of things to do.
