### ISSUE TITLE
async function error

### ISSUE THREAD

**Issue by JJJYY** [swc-project/swc#2305]
**Describe the bug**
async/await error

**Input code**
```js
function MyClass () {}

MyClass.prototype.handle = function () {
    console.log('this is MyClass handle')
}

MyClass.prototype.init = async function(param1) {
    const a = 1;

    if (!param1) {
        console.log(this)
        this.handle()
    }

    if (param1 === a) {
        return false
    }

    return true
}

const myclass = new MyClass()
myclass.handle()
myclass.init()
```

**Config**
none

```json
{
    "env": {
        "targets": {
            "chrome": "42"
        }
    }
}
```

**Expected behavior**
```
// log is:
this is MyClass handle
MyClass {}
this is MyClass handle
```

**Version**
The version of @swc/core:
v1.2.91

**Additional context**
no

**Comment by dwoznicki** [comment]
I take it you're getting output like

```
this is MyClass handle
undefined
(node:92440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'handle' of undefined
```

?

**Comment by JJJYY** [comment]
> I take it you're getting output like
> 
> ```
> this is MyClass handle
> undefined
> (node:92440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'handle' of undefined
> ```
> 
> ?

yeah, I got this error in chrome

**Comment by dwoznicki** [comment]
@kdy1 It looks like the problem is that swc binds `this` to the output function declaration.

```javascript
MyClass.prototype.init = (function(param1) {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(param1) {
        // Function body omitted because it's not important
    }).bind(this)); // <-- Here
    return function() {
        return _ref.apply(this, arguments);
    };
})();
```

Note that babel gets this right and correctly does not add `.bind(this)` to the `_asyncToGenerator` function.

My intuition is that the solution is to not bind `this` for async functions defined on the `prototype` object, but I don't see an easy way in `ecmascript/transforms/compat/src/es2017/async_to_generator.rs` to tell if the function expression is defined on a prototype. Any thoughts?

**Comment by kdy1** [comment]
I think injecting a variable like `var _this = this` will fix the issue.

**Comment by kwonoj** [comment]
I'm hitting this as well, will try to dig bit if I can come up with changes.
