### ISSUE TITLE
IIFE prevents minification?

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#2591]
**Describe the bug**

**Input code**

```js
(() => {
	var LONGNAME = 1;
	console.log(LONGNAME);
})();
```

**Config**

```js
const fs = require("fs");
const { minify } = require("@swc/core");
// const { minify } = require("terser");

let config = {
	sourceMap: { filename: "dist/index.js" },
	toplevel: false,
	module: false,
};

minify(fs.readFileSync("index.js", "utf8"), config).then(({ code, map }) => {
	console.log(code);
});

```

**Expected behavior**
Same minified output as terser:
```js
console.log(1);
```

(Most importantly that the variable names are at least renamed, better inlined, and ideally the now redundant IIFE is removed)

**Current behavior**
Only whitespace is removed
```js
(()=>{var LONGNAME=1;console.log(LONGNAME)})()
```

**Version**
The version of @swc/core: both 1.2.105 and 1.2.106

**Comment by vramana** [comment]
Even without IIFE, swc doesn't seem to minify the code to the expected behaviour. [Check here][url]


[url]: https://swc-play.vercel.app/?version=1.2.106&code=H4sIAAAAAAAAAytLLFLw8fdz93P0dVWwVTC05krOzyvOz0nVy8lP14DJaFpzAQBQtWgpKQAAAA%3D%3D&config=H4sIAAAAAAAAA2WTS5LjIAyG78K6tzOLPsDs5gyUAsJRj3kUEum4Urn7iNgxiXuHPn705ma%2B2JnPmylQGWs%2F8ZIErubTyFKQXaUi5sMIKwowM97VgDqhqAT5l97NOTNutx8mUqKwdE8ux1KRuZ%2F1RYuYRA2pTWVQa%2F7erVPOM0L6YVtgS0lwwrrfuTzPUBjtBTrcwvZgUIlzehHG0gS9LTWXF5o8CeWk757MI3jrsh9VeKrohC44NOpENYk1syHr0OOpTVPv3qrEC8wNBHf7%2BmiDhnyScyYWG9rIdSVvia5oLXIlFGxFaXX385UpvSn%2BIWqSMzAniPiOg87gQH6KKAWdnyxPqLMdGSWctCxLFPbaesZYhYabir457MW5I3vNlMmjxRC0y4N9k7jzcNU3MIfd1HbBiLxa9n2PNtgnf2R%2FNCF5mcGGI8j5gHiJpzwf30eUc%2FZHqvVLPrCq63otB9iSR20t%2BsEbPy39UxHStC%2FWvYPsWwe3Rxsen%2B23uY%2F%2FtW0g8d9N%2BHD0H4c8OOnRAwAA

**Comment by alexander-akait** [comment]
@vramana Please create a new issue, it is not related to this

**Comment by alexander-akait** [comment]
Without IIFE, we have the problem, I think here two problems

**Comment by mischnic** [comment]
Without the wrapper, it should only rename them if `toplevel` or `module` are set to true (that might be nice to have in the REPL options, by the way).

But you're right, even setting `toplevel` to true doesn't rename or inline the variable.

**Comment by kdy1** [comment]
Seems like issue of config or regression.
I tried this on https://swc-play.vercel.app/ which uses `v1.2.102`.
(target = 2021, minify = true, compress = true, mangle = true)

But it didn't work if config is (target = 2021, minify = true, compress = false, mangle = false)

**Comment by mischnic** [comment]
I think my confusion here was that with terser, `mangle` and `compress` are `true` by default.
But they are disabled by default for swc. So I think we can close this unless you want to change these defaults

**Comment by kdy1** [comment]
I think `compress` and `mangle` should be true by default, but I made a mistake while declaring types.
Thanks!
