### ISSUE TITLE
Pretty-formatted diagnostics

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#2860]
### Describe the feature

Context: https://discord.com/channels/889779439272075314/889780921002246154/912939004159221790

Current diagnostics output from swc is good. But I'm curious if we have prettier output similar to what rust cli, or some other cli offer. Something looks like https://twitter.com/_lrlna/status/1462797187276939268 can be a good reference example. 

Actually above error diagnostics is from https://github.com/zkat/miette - if we could adapt it without heavy modification it may be a good way to go. Unfortunately we may need features like https://github.com/zkat/miette/issues/64 as far as know to utilize it. 

This issue is tracking purpose to casually look for possible approaches to achieve diagnostics report. It should be fine to use some external libs or if we build it for ourselves. @kdy1 suggested 

> we may implement ansi Handler and result would be similar

as possible alternative we can consider.

**Comment by kwonoj** [comment]
I assigned myself for casual exploration, but this doesn't mean I own this: if anyone have ideas or suggestions / PRs, it is hugely welcome.

**Comment by zkat** [comment]
p.s. I've been thinking of using swc with another project and I'm happy to talk modifications to miette if it can be shaped in such a way that it's useful to swc. It's definitely the kind of application I want it to work for!

**Comment by kdy1** [comment]
@zkat I did some experiments using it, and I need some help.
Due to the signature of `SpanContents`, I used `Box::leak` at https://github.com/kdy1/swc/blob/1cb2aaf00b90b518f0d2fd8517ae4984cc451913/crates/swc_reporter/src/lib.rs#L268-L271
How can I remove this?

**Comment by zkat** [comment]
You'd have to change the signature for the data field in SpanContentsImpl to `data: Vec<u8>` and convert from string to `Vec<u8>` when you instantiate the SpanContents.

**Comment by kdy1** [comment]
I mean I want a way to make borrow checker happy about the `'a` in the return type (`&'a [u8]`)
Seems like I should somehow create owning reference

**Comment by zkat** [comment]
Ahhh ok. I actually spent some time on this rather than responding when I'm really tired, and you're right.

The short version is that miette basically expects that `&'a [u8]` to be a reference to your `SourceCode`, which has worked out so far for projects using miette that happened to just thread references through.

But I see that swc doesn't do that: all its methods that return the contents of some section of your `SourceMap` use `Arc` instead of plain `&` to refer back to the content.

So there's basically two solutions here:

1. swc rearchitects itself to switch to plain references and carefully figures out how to thread `SourceMap` references through its various methods. This... would probably be a little faster, but have some cost in flexibility.
2. miette changes the signature for `SpanContents::data` to `fn data(&self) -> String`, which would be a breaking change, but probably not affect most consumers because those just use the built-in `SpanContents` implementation on String and such. This would have a cost in terms of allocations buuuuut I think it's going tobe fairly small, because `SpanContents::data()` only gets called once for each error section in the renderers. The change _would_ be a good chunk of a rewrite of some miette internals but I think it's manageable.

What do you think?

**Comment by kdy1** [comment]
I think `fn data(&self) -> &str` or `fn data(&self) -> &[u8]` would be the best.
Problem is that it requests longer lifetime than `&self`.
I'd love it if you changes it, thank you in advance!

**Comment by kdy1** [comment]
I found the solution using `transmute`.
Now I'm working to find a wat to test it and render suggestions as children
