### ISSUE TITLE
Semicolon / Object destructuring with default calls on default

### ISSUE THREAD

**Issue by dbo** [swc-project/swc#3316]
### Describe the bug

Having a line without semicolon following an object destructuring with default init calls on the default

### Input code

```typescript
var bar;
const baz = 'ok'  // no semicolon
({
    foo: bar = baz
} = {});

console.log("result:", bar, baz);
// expected result: ok, ok
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.130&code=H4sIAAAAAAAAAy3MTQqDMBAF4P2c4uFGC6J7xcPYdFqKaZ4kaSmKd3dSOjA%2Fi2%2FeZ464znEUx5CynRsm1FxqoO8RiKSvp6NnkGYXWN3JobyYMy2H7f24jPJLoNfO89FUUdPb56FqCy1jM2KJ%2Bl3VZb3hD8CltT4BRxk5SIcAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

not calling on the default

### Actual behavior

var bar;
var ref;
var baz = ('ok')((ref = {}, (baz = ref.foo, bar = baz === void 0 ? baz : baz), ref));
console.log("result:", bar, baz); // expected result: ok, ok

### Version

1.2.130

**Comment by RiESAEX** [comment]
1. It should result in the error `"ok" is not a function` or `baz is not defined`, depending on whether the target supports `const`. since there is not a semicolon it becomes call function ok with a object destructuring as args.
2. for input like 
```js
({
    foo: bar = baz
} = {});```
it should transform to 
```
```js
var _ref = {};
var _ref$foo = _ref.foo;
bar = _ref$foo === void 0 ? baz : _ref$foo;
_ref;
```
not 
```js
var ref;
ref = {}, baz = ref.foo, bar = baz === void 0 ? baz : baz, ref; // bar will always be baz 
```

**Comment by kwonoj** [comment]
Closing as #3326 suggested to fix this.
