### ISSUE TITLE
Decorator-based dependency-injection not working (NestJS / TypeORM)

### ISSUE THREAD

**Issue by vith** [swc-project/swc#3592]
### Describe the bug

Fields decorated like this:

```ts
  @InjectRepository(User)
  private userRepo: Repository<User>;
```
are not being defined when `swc` is used

### Input code

Freshly created NestJS project with minimal reproduction:

https://github.com/vith/nest-swc-test

```console
$ pnpm run start
...
this.userRepo is present
```

```console
$ pnpm run start:swc
...
this.userRepo is undefined
```

https://github.com/vith/nest-swc-test/blob/main/src/other/other.service.ts is the main file for the issue reproduction

### Config

```json
{
  "jsc": {
    "baseUrl": ".",
    "paths": {
      "src/*": ["src/*"]
    },
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    },
    "target": "es2020",
    "externalHelpers": true,
    "transform": {
      "legacyDecorator": false,
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

expect `this.userRepo is present` to be logged

### Actual behavior

`this.userRepo is undefined` is logged

### Version

'@swc/core': 1.2.140

### Additional context

also tried ` "legacyDecorator": true,`; same result

**Comment by KevinGruber** [comment]
I can second that we also run into that problem with our custom DI solution which has property injection support.

Would be cool to get that fixed :-) 

Thanks for your awesome work on swc.

**Comment by williamtetlow** [comment]
The problem is related to this https://www.typescriptlang.org/docs/handbook/decorators.html#property-decorators

> NOTE  A Property Descriptor is not provided as an argument to a property decorator due to how property decorators are initialized in TypeScript. This is because there is currently no mechanism to describe an instance property when defining members of a prototype, and no way to observe or modify the initializer for a property. The return value is ignored too. As such, a property decorator can only be used to observe that a property of a specific name has been declared for a class.

When compiled with TS it won't pass the property descriptor to the decorator so nest's inject decorator will run https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/inject.decorator.ts#L48-L57

In swc (like babel proposal plugin) we pass the property descriptor and so it runs https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/inject.decorator.ts#L40-L47

@kdy1 how/should we handle this?
