### ISSUE TITLE
wrong output of export Class

### ISSUE THREAD

**Issue by troy351** [swc-project/swc#3892]
### Describe the bug

error ouput code causing `can not read property of undefined`

### Input code

```typescript
export class Foo {
  bar() {
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.150&code=H4sIAAAAAAAAA0utKMgvKlFIzkksLlZwy89XqOblUlBISizS0IQwa3m5gAgANcDmXicAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D

### Expected behavior

```js
var Foo = function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, exports.Foo);
    }
    _createClass(exports.Foo, [  // this line should be `_createClass(Foo, [` which works in the previous versions
        {
            key: "bar",
            value: function bar() {}
        }
    ]);
    return exports.Foo;
}();
```

### Version

1.2.150

**Comment by Austaras** [comment]
This is caused by #3845. I don't if that fix is right: [babel](https://babeljs.io/repl#?browsers=chrome%2044&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wQCwJYBsAmcAvHABQCUxAfHAN4BQciKqEuwAdLhAOakDkACWC5ucAOrQCAQn7kA3PQC-i-qEixmaDAENRAYRwFiZSkRoMmWPPgqKVQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=true&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D) generates same output as previous eversion, and it cannot be modified in esm anyway
