### ISSUE TITLE
Arrow Function Syntax is still Exist After Converting to ES5 Syntax

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#4088]
### Describe the bug

When I convert an arrow function syntax, it fails to convert, there is still an arrow function in the result code.
At the seventh line of the output code.

### Input code

```typescript
function f0() {
}
f0.prototype = {
    name: 'Nicholas',
    age: 29,
    job: 'Software Engineer',
    sayName() {
        v0[args](1, {
            v9: v7 => super.v3(v27),
            foo: a,
            done: 'a'
        });
    }
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.158&code=H4sIAAAAAAAAA1WOwQ6CMAyG7zxFb0BCCOKBAMGbVy4ejYeKG2J0JduYIWbv7pzEyH9qv35pyyfR6YEE8CyK4RXYgGfpKEmTnkcGjUPgIvDBKgjbobvSHVWYeIq9g3n5bW50dsaBuH6iZLAX%2FSAYk4uqcG7dDn8DlpjsiLJXp2iT%2FFE%2FKSswBTQ7UNPIZGq2kcmLOFlJnKgCXLMLic%2BfGP6ojWtf28DWb7HJBRDtAAAA&config=H4sIAAAAAAAAA22QwU7DMAyG3yXnXbnsxgQTkyjvYKUuZErsyHZHy8S7z2VTwxAnx5%2Ft3398DkeNYXsOFURRlpfOZDCFbcBYQKOkamHjbY4GyIqb0M8EJcVDqSy20irpBIYd2gf3Kx1GipaYdokaxGmZfMIBxmx74fKn8gYFtULEu1qPkQWMRf9BOxxY8Hm6s2RcX%2FGE%2BfETUqPpx7f7hBv69k4BUlfwbTTm7ADkHW25gj749zOz4i%2BXhkKQXzBXXO24TOF%2BzLhc0ebqMUQuhemoLqEmKTYX17Tjvslm%2BJrXhPhAvoVrU0%2Fa3fSv5AIhCjW1vQEAAA%3D%3D

### Expected behavior

Arrow function syntax can be converted successfully in my code.

### Version

1.2.158

**Comment by kdy1** [comment]
Seems like a regression?

**Comment by kdy1** [comment]
I investigated this and found that `FnEnvHoister` is storing the arrow expression internally and the expression is not processed by the `arrow` pass.

**Comment by Austaras** [comment]
The fix is incorrect: an arrow containing a super cannot be trivally transformed into a normal function, see [babel](https://babeljs.io/repl#?browsers=chrome%2045&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMADACgJSIN4CgC-uqAdAA4BOcUVAnqQKaIC8Oui7iYAhgLb0BciAOQA5GBAAWcADZcAzkIA0bDlwDmAxACYAnMo6IAVnABGgoQGU4wKAHcu5RgFEwamGHr1ySlezlcaEV56TFYDAwA3FABtBzU5AF00AEZFMPCMiJ1BCIB2ZgA-RDkQBnJiCIBmNAitXIx9DPDgODhBLkamjgATBE0hLiFfcPwMAG5hwnwxoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%22noClassCalls%22%3Atrue%7D)

**Comment by kdy1** [comment]
Oh, I see. Thank you and reopening ...

**Comment by kdy1** [comment]
I'll revert the wrong fix with https://github.com/swc-project/swc/pull/4093
