### ISSUE TITLE
swc minify result is bigger than terser and esbuild

### ISSUE THREAD

**Issue by guoyunhe** [swc-project/swc#4117]
### Describe the bug

I am testing different kinds of JS minifiers and found swc generates bigger output than terser and esbuild:

- unminified: 4.7MB
- terser: 1.8MB
- esbuild: 1.9MB
- swc: 3.1MB

swc's output is 72% bigger than terser and 63% bigger than esbuild.

Details can be found here https://github.com/guoyunhe/benchmark-js-minifiers

### Expected behavior

swc should output similar minified size as terser and esbuild

### Version

1.2.159

**Comment by kdy1** [comment]
Your config is wrong.

![image](https://user-images.githubusercontent.com/29931815/159420393-ce2fb33a-62e8-41ee-b17b-a64981be3554.png)


```
const { SWCMinifyPlugin } = require("swc-webpack-plugin");

module.exports = {
  mode: "production",
  entry: "./sample.js",
  output: {
    path: __dirname + "/dist/swc",
  },
  optimization: {
    minimize: true,
    minimizer: [new SWCMinifyPlugin({
      jsc: {
        minify: {
          compress: true,
          mangle: true
        }
      },
      minify: true
    })],
  },
};

```


I'm not sure why `swc-webpack-plugin` uses `.transform` instead of `minify` though. 
It's much slower because it enables compat transforms.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/29931815/159420587-a68b7f57-231e-4f72-92e7-e78709d695bd.png">


It's not an official plugin, though.
