### ISSUE TITLE
Block scoped function isn't correctly transformed

### ISSUE THREAD

**Issue by Austaras** [swc-project/swc#4882]
### Describe the bug

In ES6 and after, function declaration is strictly block scoped.

### Input code

```typescript
if (false) {
  function foo() {}
}

console.log(foo())
```

### Playground link

https://play.swc.rs/?version=1.2.196&code=H4sIAAAAAAAAA8tMU9BIS8wpTtVUqOZSUEgrzUsuyczPU0jLz9cACtVy1XJxJefnFefnpOrl5KdrgMU1AXK46TA2AAAA&config=H4sIAAAAAAAAA0WMQQ7DIAwE%2F%2BIz1174Qx9hUSciAoxsRypC%2FL2gJsrJ1u7sdDg0gO9QUZRkfdqK4Rc8UMioQWI1cBObkclJw4Gh7GSL0NesErMS%2BA2TkoMcS9zaEgXOVUj1qbDs6SbHFGX%2BnCvoYK3OuyaZy6EwHtE1jvq%2B6P%2F8B7PHho66AAAA

### Expected behavior

```js
if (false) {
    var _$foo = function _$foo() {};
}
console.log(foo());
```

### Actual behavior

```js
if (false) {
    var _$foo = function _$foo() {};
}
console.log(_$foo());
```

### Version

1.2.196

**Comment by Austaras** [comment]
This is actually more complicated -- according to [spec](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-functiondeclarations-in-ifstatement-statement-clauses), browser could have extra behavior for scoped function. However babel and nodejs -- they're not browsers anyway -- don't implement that. And in both chrome and firefox, under strict mode, scoped function wouldn't be exposed to outer environment, which is also the behavior of terser. I don't know which one is the correct thing to do

**Comment by overlookmotel** [comment]
Just FYI, the behavior in sloppy mode gets very complicated indeed. A function nested in a block creates *two* independent variable bindings, with an unintuitive order of initialization.

Please see in illustration [here](https://github.com/babel/babel/pull/14203#issuecomment-1038187168) in conversation around a PR I initiated on Babel to fix this same issue. I'm afraid I've largely abandoned the attempt to fix in Babel due to these complications, and the fact that it's quite an uncommon case. So I never entirely pinned down the correct behaviour.

**Comment by Austaras** [comment]
Thanks for the info! After find out there's cross browser incompliance in block scoped function, I decided to only implement what's written in spec.

**Comment by Austaras** [comment]
~~or at least what's in spec according to my interpretation~~
