### ISSUE TITLE
Add `module.exports` statement to default export when compiling to CommoJS

### ISSUE THREAD

**Issue by wintercounter** [swc-project/swc#5154]
### Describe the feature

Currently, if I use SWC to compile a library, it won't add `module.exports` for default exports. This forces users to use my library as `require('library').default` which I'd like to prevent. I'd like to have an option to add `module.exports` when compiling CommonJS for NodeJS.

On the following Playground link, you can see that `module.exports` is not being added.

https://play.swc.rs/?version=1.2.210&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUTA0AgAi1LZlEQAAAA%3D%3D&config=H4sIAAAAAAAAA3VTy5LjIAz8F845zOa0NR8wt%2F0GlwLCUdYGCglPXKn8%2B4rY8SOZvaGmBS21dDMXtubzZhJkxlxPPAaBq%2Fk0aHtgmymJOShNIQ8d4%2F1gBHKLUil8%2FDge9bqLkXEmHExPgfxYH7OxTxmZ61mTSo9BeOFBzvFbQ8lFo1OMHUJ4ixvghoJgi3lNtbHrIDE2A%2BQlo%2F4GmTiGHVQEXZNyTNv04EgoBg0X0CG4xka3FuIooxUacEPSd5QUWMXtQYen0ra1idPXOEBXQHCJr49W6KdL3jkSS%2BNL4BdoVjslTtBU6Mwi32SUksOTc4kUdr34i6g6O2AO0G%2F0P3CvXuyZ%2FgcWBa9Gyrig6vKqKmCrxTVEfqmwqsYshAspoysWa4V2fXwGdwUxOWzQe233kszfJPa8USVjwuiXe20b%2BNWEKWyeQ7VH6xy8gV8qS7Z%2BzHgPcn7FeOxPsXt7okc5R%2FcGayckvoJZR%2FiaXtESHGqf0W0uCtewVqnb1kNo66zdjMTU4YDd3qb%2FmvwDljIN1bX9NhD%2BXo0AHQ769fHc9ntVEF2ZFagDuvfazT6GC5v7uuzPt%2FjPzH7I%2Fwd%2FzDlpYQQAAA%3D%3D

### Babel plugin or link to the feature description

https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by kwonoj** [comment]
I feel this is fairly expected behavior, which even referred plugin mentions babel/core removed those behavior. Should this be included in swc/core?

**Comment by kdy1** [comment]
It's expected

**Comment by kmalakoff** [comment]
I write and test my libraries on Node >=0.8 which doesn't support the module format that swc exports...

```
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return A;
    }
});
```

Since you support commonjs and ES3, I think it is fair that you support Node.js environments that existed when those versions of node existed, eg. module.exports = /* the default export */

Until swc 1.2.205, I was able to replace 'exports.default = ' with 'module.exports =, but after that version, I cannot use newer versions of swc.

Could you please provide support for module.exports or https://www.npmjs.com/package/babel-plugin-add-module-exports or some other method of supporting older versions of Node?

Here's an example module that I compile from typescript to both cjs and esm formats: https://github.com/kmalakoff/response-iterator/tree/master/dist

**Comment by magic-akari** [comment]
@kmalakoff Are you looking for something like `interopClientDefaultExport` in next.js?
https://github.com/vercel/next.js/blob/20b63e13ab2631d6043277895d373aa31a1b327c/packages/next/taskfile-swc.js#L118-L125

**Comment by kmalakoff** [comment]
@magic-akari that is exactly what I was looking for! Thank you for sharing this
