### ISSUE TITLE
(Possibly) Bug of parsing CSS `@document` without quotes 

### ISSUE THREAD

**Issue by g-plane** [swc-project/swc#5217]
### Describe the bug

When parsing the code below, the CSS parser would report an error. It looks that the URL in the code below must be quoted, but other parsers, for example, all the parser at [astexplorer.net](https://astexplorer.net/) and the parser of CSS language server inside VS Code, accept the code.

There's no online playground for parser of CSS language server of VS Code, but the screenshot below shows no syntax errors:

![image](https://user-images.githubusercontent.com/17216317/179206735-a6e3dbcc-f163-4d3a-a5f3-538bb7194e4e.png)

The warning in the screenshot just complains about unknown at-rule, which is unrelated to this issue.

### Input code

```css
@document domain(http://www.example.com/) {}
```

### Playground link

https://swc-css.netlify.app/?code=eJxzSMlPLs1NzStRSMnPTczM08goKSmw0tcvLy_XKzfWyy9K19dUqK4FAB-JDds

### Expected behavior

Maybe the parser the should accept the code above and reproduce AST.

### Actual behavior

The SWC parser reported an error: `Unterminated block comment`. It **isn't** an recoverable error.

### Version

`swc_css_parser` crate: 0.108.0

**Comment by g-plane** [comment]
cc @alexander-akait

**Comment by alexander-akait** [comment]
Thank ypu fro remort, I will look at this

**Comment by alexander-akait** [comment]
Hm, regarding spec, only `<string>` allowed in `domain`, anyway you are right we should not fatal failed here, anyway recenstly I fixed all fatal fails in CSS parser, so you should not get this error for the latest version, here example https://github.com/swc-project/swc/pull/5228

**Comment by g-plane** [comment]
Yes, I've checked the spec and it says only `<string>` is allowed. It's already an recoverable error, but most other parsers allow this case, or is there a special "mark" (e.g. a special enum variant of `ErrorKind`) to distinguish this error?

**Comment by alexander-akait** [comment]
@g-plane Yes, agree, we should improve it, our parser is not handle all functions https://github.com/swc-project/swc/blob/main/crates/swc_css_parser/src/parser/at_rule.rs#L1070, I think we should change `else` branch, I missed it because `@document` is removed from the spec and I don't see someone uses it in real code :smile: 

Error handling here https://github.com/swc-project/swc/blob/main/crates/swc_css_parser/src/parser/at_rule.rs#L1095, most of our places in parser use `ErrorKind::Expected`, it looks good for output, but not good for DX, so I am fine to use a special enum
