### ISSUE TITLE
Update Wasmer to 3.0.0-beta

### ISSUE THREAD

**Issue by syrusakbary** [swc-project/swc#5480]
### Describe the feature

SWC currently uses Wasmer 2.3.

We have revamped Wasmer API, solving one main issue that SWC had when using Wasmer in JS: https://github.com/wasmerio/wasmer/issues/2816.

Right now I believe Wasmer API for 3.0 is stable enough to start trialing it with SWC and test it on higher loads before reaching the Release Candidate, so it would be great if the project can start trialing it!

Migration docs: https://github.com/wasmerio/wasmer/blob/master/docs/migration_to_3.0.0.md

**Comment by kwonoj** [comment]
@syrusakbary I was few days faster https://github.com/swc-project/swc/pull/5456 😅 

However, we are having some regressions in current main branch so until we figure it out we can't really upgrade unfortunately.

**Comment by kwonoj** [comment]
@syrusakbary We tried wasmer@3 and reverted it via #5521. To isolated upgrade, we created new `@swc/core` release contains 2 changes - one for rkyv bump (https://github.com/swc-project/swc/pull/5507) and another for wasmer bump https://github.com/swc-project/swc/pull/5521. Once host (`@swc/core`) have those changes, when wasm binary calls exported fn it traps like

```
RuntimeError: out of bounds memory access
```

It even occurs with fn call doesn't involve any serialization / deserialization of data, for example a fn try to return `u32` could raise same.

We did a couple of bisect across swc's commit history, and we are certain offenders are in between those 2 commits. I can't tell if it's due to some misconfiguration on SWC's end or somewhere else though.

**Comment by syrusakbary** [comment]
Hey @kwonoj could we have an easy way to reproduce this, even if it's on this repo? (what command can we run to reproduce the trap you reported?)

**Comment by kwonoj** [comment]
Unfortunately there's no easy steps to reproduce, you have to generate specific host binary with wasm. I'm afraid it's not easy to create reproducible, isolated codebase as well.

**Comment by syrusakbary** [comment]
You know if it may be possible to have part of that code to create a test case on this repo @kwonoj?
I believe it will also be useful for the project, since it will expand the test coverage!

We would like to investigate and fix but without any way to reproduce it's going to be quite challenging 😢

**Comment by kwonoj** [comment]
I am aware isolated repro case is key to debug, howeve this is very convoluted and we (me and kdy) both failed to correctly dig further to create those. The closest thing we could do is bisecting that wasmer + rkyv bump commit could cause those. 

Wish I could spend more time but there are other priorities so may not able to back on this for a while.

**Comment by ExProbitasFiducia** [comment]
@syrusakbary 

I'm getting this with wasmer 3.1.1 and 3.0.1

I have an issue I think with features because according to api/lib.rs sys and js *cannnot* be enabled at the same time,

https://github.com/wasmerio/wasmer/blob/master/lib/api/src/lib.rs#L419-L422

 but rust is telling me an import is ambiguous:
 
 
 ```
error[E0659]: `AsStoreRef` is ambiguous
   --> /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.1.1/src/js/ptr.rs:238:43
    |
238 |     fn is_from_store(&self, _store: &impl AsStoreRef) -> bool {
    |                                           ^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `AsStoreRef` could refer to the trait imported here
   --> /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.1.1/src/lib.rs:433:9
    |
433 | pub use sys::*;
    |         ^^^^^^
    = help: consider adding an explicit import of `AsStoreRef` to disambiguate
note: `AsStoreRef` could also refer to the trait imported here
   --> /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.1.1/src/lib.rs:439:9
    |
439 | pub use js::*;
    |         ^^^^^
    = help: consider adding an explicit import of `AsStoreRef` to disambiguate
```

**Comment by kwonoj** [comment]
While there are remaining issues, swc/core uses 3.2 at least.

**Comment by ExProbitasFiducia** [comment]
ah this is awesome news!!
