### ISSUE TITLE
Remove minification apis from `transform()`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5527]
I think this is a mistake.

We should provide `minify()` and `transform()` independantly

**Comment by Austaras** [comment]
So If user want to transform then minify some code, they would run parse and codegen twice?

**Comment by kdy1** [comment]
Hmm
It's definitely a problem...



I'll think more about this

**Comment by kwonoj** [comment]
In a high level, maybe it's worth thinking about `pipeable` operator design in swc. Instead of chaining execution per each interfaces in the v8 context, allow to queue its execution in the pipe, then execute it all then pass back to result into v8. This'll reduce serialization / deserialization per each invocation if someone want to chain numbers of operations like transform -> minify, transform -> bundle, or any combinations. Don't have good ideas of `how` part though.
