### ISSUE TITLE
swc removes variable/function declaration when using the jsc.transform.optimizer.globals.var option 😢 

### ISSUE THREAD

**Issue by GiancarlosIO** [swc-project/swc#5714]
### Describe the bug

For some reason, the code that exports the const useContactData is removed 🤔 . It only happens if a use the  `jsc.transform.optimizer` option.

As you can see, the var `useContactData` is empty 🤔 

![image](https://user-images.githubusercontent.com/17274950/188019455-a4ca408f-968c-4ba9-badc-7c586323bc9c.png)

### Input code

```typescript
/* eslint-disable */
import _objectSpread from '@babel/runtime/helpers/objectSpread2';
import _slicedToArray from '@babel/runtime/helpers/slicedToArray';
import { useMutation } from '@apollo/client';

const ADD_CONTACT_DATA_MUTATION = {};

export var useContactData = function useContactData() {
  return {
    data: 2,
  };
};

export default useContactData;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "transform": {
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "development": false,
        "useBuiltins": false,
        "throwIfNamespace": true
      },
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.246&code=H4sIAAAAAAAAA33NsU7DMBCA4T1PcVtLBbLUkQoJK1kY2g6YObo4F2Hk2NH5XIGivjsmEtAysPnufn1WG6DkXZC73iXsPMFGVW6cIgu0sXsjK88TE%2FYwcBxh9dhhR15xDuJGUq%2FkJ%2BKkLsvtavcjFNpSb6Jmxo%2F%2Fiav0l5ghJ9pnQXExwPnbwCl6H5X1joKUurIxJAHdNG19PBhdm7bRRrf7F6PN0%2FEADzCfS0bvi3pC%2FnLrGAStNChYgiEHu%2FxyfVnfwFwBMEnmsDwB%2BrK%2Fh%2B1tGYp6Afc0YPbyh9hVn3ENgytoAQAA&config=H4sIAAAAAAAAA0VQy07EMAz8F59XCJDg0OOKBXGAAxLnymTdEpSX7HShVP137Lbs5pDY4%2FF4nAm%2BxEEzQUEWYotkTBV%2FoIE6FhLHvlTYQRWFOgxCsyaMSbrM0fhM6OoiwdhH1MY3Q66cFiodAkVKprCWH%2FU%2BUyzZqkc6UchlydY5OxiE9oMP1Sc5Y%2FWT8%2Fdz94qRpKAjaCoP5imX6qP%2FXXfoQ%2F5QvoUnXczetn047N%2Bf2tY20xaY9ageck86Ekhur2%2Fu1EnIWeg8L%2Frku9EEXI6FSS5WIqY%2B%2FDNNK%2BbjYMC0fN2ieQ%2FzRWPr8%2FKyERfrf5cmEXCDAQAA

### Expected behavior

The expected code should be:

```tsx
const ADD_CONTACT_DATA_MUTATION = {};
export var useContactData = function useContactData() {
    return {
        data: 2
    };
};
export default useContactData;

```

Where useContactData has the correct function definition.

### Actual behavior

It removes the code that doesn't need to be removed.

### Version

1.2.246

**Comment by kwonoj** [comment]
Isn't it expected behavior?

https://swc.rs/docs/configuration/compilation#jsctransformoptimizersimplify

Doc clearly mention

> You can set this to false to use inline_globals while skipping optimizations

which seems to work:

https://play.swc.rs/?version=1.2.246&code=H4sIAAAAAAAAA33NsU7DMBCA4T1PcVtLBbLUkQoJK1kY2g6YObo4F2Hk2NH5XIGivjsmEtAysPnufn1WG6DkXZC73iXsPMFGVW6cIgu0sXsjK88TE%2FYwcBxh9dhhR15xDuJGUq%2FkJ%2BKkLsvtavcjFNpSb6Jmxo%2F%2Fiav0l5ghJ9pnQXExwPnbwCl6H5X1joKUurIxJAHdNG19PBhdm7bRRrf7F6PN0%2FEADzCfS0bvi3pC%2FnLrGAStNChYgiEHu%2FxyfVnfwFwBMEnmsDwB%2BrK%2Fh%2B1tGYp6Afc0YPbyh9hVn3ENgytoAQAA&config=H4sIAAAAAAAAA0VQsU7EMAz9F88nBEgwdDxxIAYYkJgrk3NLUNJEdnpQqv47dq70MiT2e8%2FPdmb4EgfNDBlZiC2SaSj4Aw2UKZM49rnADooo1GEQWjRhHKRLHE3PhK5UC8Y%2Boha%2BGXLllCh0CBRpMIcz%2Faj3JrFkZY90opByzc59djAK7Ucfih9kw8onp%2B%2Fn7hUjSUZH0BQebaaUi4%2F%2Bd93Bxxx8N21lfUgfGhl30k3tbduHw%2F79qW1tVfWARY82QO5JZwCS2%2BubOx0tpCS0OUU%2FVOMZXIqZSS6zRRz68K80r5iOowFz%2FcvqeQ%2FLxWOt8%2FKyCusuf8D7bF%2BUAQAA
