### ISSUE TITLE
Chained `jest.mock` calls not recognized by the compiler

### ISSUE THREAD

**Issue by zaesur** [swc-project/swc#6540]
### Describe the bug

The Jest documentation specifies that `jest.mock` returns the `jest` object ([link](https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options)). However, when running a test with chained `jest.mock` calls, it seems that they are not recognized by the compiler.

### Input code

```typescript
import foo from "./foo";

jest.mock("./foo").mock("./bar");

test("Foo is a mock", () => {
    expect(jest.isMockFunction(foo)).toBe(true);
});
```

### Expected behavior

I'd expect the test described above to pass, just like the following:
```js
import foo from "./foo";

jest.mock("./foo");
jest.mock("./bar");

test("Foo is a mock", () => {
    expect(jest.isMockFunction(foo)).toBe(true);
});
```

### Version

1.3.20

**Comment by mramirarab** [comment]
@zaesur I also observed the same problem but to me it seems like the problem is with hoisting the mocks i.e. when used as jest.mock, the mocks are correctly hoisted as expected. However, the moment there are chained mocks, only the top level ones get hoisted. And because of lack of hoisting, the imports happen before the mocks and that is why the modules that have been imported don't have the mocked implementation. So maybe a bug to SWC/jest?

**Comment by kdy1** [comment]
@mramirarab The code for jest transform lives in the main swc repository
