### ISSUE TITLE
`swc_ecma_parser::parse_args` memory consumption

### ISSUE THREAD

**Issue by Boshen** [swc-project/swc#6966]
### Describe the bug

Background: I'm currently investigating memory issues in rspack, it's currently using GBs of memory.
I'd like to reduce as much memory as possible.

---

In `parse_args`,

https://github.com/swc-project/swc/blob/5a5a7d70e4ad56fb78c75118452557faec6caead/crates/swc_ecma_parser/src/parser/expr.rs#L715

it's currently allocating 8 * `ExprOrSpread` (32 bytes) = 256 bytes for every arg.

And from the profiler:
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/1430279/220008874-6e7e39b5-1554-4c71-abb9-3b753b608063.png">

So would it be possible to reduce this allocation by either removing the capacity or shrink the capacity afterwards?

### Expected behavior

Use less memory.

### Version

main

**Comment by IWANABETHATGUY** [comment]
I noticed this modification line was introduced in https://github.com/swc-project/swc/pull/2313/files#diff-6025cbe7e6c0cc4a05f698222345ba4f8a8b2850539f8e2410f1309878ef56df, but I think the original code would not cause a performance issue, because most of the functions have only 1-4 arguments, I think to reduce the preallocation to `2` maybe a better idea.
