### ISSUE TITLE
Different output for properties between TS and JS

### ISSUE THREAD

**Issue by rentalhost** [swc-project/swc#7032]
### Describe the bug

To be honest, I don't know if it's a bug, but it's pretty weird.

When I use SWC in a JS context, when compiling a class that defines a undefined-value attribute it will be displayed in the output as-is. However, in the TS context they will not be.

### Input code

```typescript
export class Example {
    aProperty;

    constructor() {
        this.aProperty = false;
    }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.38&code=H4sIAAAAAAAAA0utKMgvKlFIzkksLlZwrUjMLchJVajm5VIAgsSAovyC1KKSSmteLohIcn5ecUlRaXJJfpGGJkwZCJRkZBbrwdUr2CqkJeYUp1pDFNTyctUCAM%2Fcg7xoAAAA&config=H4sIAAAAAAAAAxWKQQqAMAwE%2F7JnD5JjfxNKFEWkZHNoKfm79TYzzMTNijLR1Gn%2BE8cb2lEQoxmrXy2wIbjSoQ8tl6ifFmsxyi6CzA%2Br99KJSAAAAA%3D%3D

### Expected behavior

```js
export class Example {
    constructor(){
        this.aProperty = false;
    }
}
```

### Actual behavior

JS context:

```js
export class Example {
    aProperty; // The property is keeped.
    constructor(){
        this.aProperty = false;
    }
}
```

TS context:

```js
export class Example {
    // The property is not declared.
    constructor(){
        this.aProperty = false;
    }
}
```

### Version

1.3.38

**Comment by magic-akari** [comment]
This is because the useDefineForClassFields option has different preset settings in SWC for JavaScript and TypeScript.
By default, useDefineForClassFields is turned off in TypeScript, but if you [enable this option][TS With useDefineForClassFields true], you will see the same output as in JS.

- Related issue: #6985 

[TS With useDefineForClassFields true]: https://play.swc.rs/?version=1.3.38&code=H4sIAAAAAAAAA0utKMgvKlFIzkksLlZwrUjMLchJVajm5VIAgsSAovyC1KKSSmteLohIcn5ecUlRaXJJfpGGJkwZCJRkZBbrwdUr2CqkJeYUp1pDFNTyctUCAM%2Fcg7xoAAAA&config=H4sIAAAAAAAAAx2MMQrDMBAE%2F3K1i6BSbYL%2FcdiroKDI4vYMMUZ%2Fj%2BxuZxj2lA8Xiac0NcKuxaO6%2FiSKHw1cLDeXSZxDJS1EH2BamTb7Xv1OvJByxbzZsyg5Z5SVEt32O1Z7w8cfGB4hSO9%2FPRC9xnUAAAA%3D

**Comment by rentalhost** [comment]
Nice! I will close this issue in prior to #6985.
