### ISSUE TITLE
`import '...' with {...}`

### ISSUE THREAD

**Issue by arcanis** [swc-project/swc#7179]
### Describe the feature

The `import '...' assert {...}` syntax got changed into `import '...' with {...}` at the [last tc39 meeting](https://dev.to/hemanth/updates-from-the-95th-tc39-meeting-ne5).

### Babel plugin or link to the feature description

https://github.com/tc39/proposal-import-attributes

### Additional context

The purpose of this change was only to explicitly allow runtimes to include the attributes in the module cache key (instead of just validating that the target module was matching the constraint), so it shouldn't need other changes in SWC other than adding support for the new syntax.

**Comment by nicolo-ribaudo** [comment]
Fyi, Babel is probably going to release support for this next week. I am also working on support for Rollup and Webpack (https://github.com/xtuc/acorn-import-assertions/pull/21). It would be nice to have all the major tools supporting this in the next few months, so that the community can start migrating :)

**Comment by kdy1** [comment]
This is stage 2, so I'm not going to work on this.

**Comment by nicolo-ribaudo** [comment]
Its stage 3 _pending reviews_ from other delegates to make sure that the spec text is correct. It already received two out of three reviews (https://github.com/tc39/proposal-import-attributes/issues/137) — I'll ping again when the third one is done because then the proposal will automatically have real stage 3.

**Comment by lukastaegert** [comment]
@nicolo-ribaudo aren't the reviews done by now?

**Comment by nicolo-ribaudo** [comment]
I'm sorry, I forgot to ping 😅

This is now been implemented in v8 (flagged) and JSC (unflagged), and is being implemented in TypeScript.

**Comment by kdy1** [comment]
I'll work on this today or tomorrow
