### ISSUE TITLE
jsc.minify.format.inlineScript support 

### ISSUE THREAD

**Issue by 9aoy** [swc-project/swc#7602]
### Describe the feature

https://swc.rs/docs/configuration/minification#jscminifyformat

![image](https://github.com/swc-project/swc/assets/22373761/109cc4b6-b000-470b-853d-f39a9cff872c)

input:
```
 "<script></script>"
```
expected output:

```
 "<script><\\/script>"
```

**Are you willing to work on this yourself?**
yes

### Babel plugin or link to the feature description

https://github.com/terser/terser/blob/aeddfabd04ace5a6565b2920b074ad7dc210bcac/lib/output.js#L367

**Comment by Skalman** [comment]
FWIW, the Terser implementation isn't complete, so the linked code isn't sufficient to make it completely safe.

I've filed an issue with Terser: https://github.com/terser/terser/issues/1408

**Comment by fabiosantoscode** [comment]
I'm implementing this with a simple lookup of the latest printed stuff before printing.

For example I'm going to check if the output stream ends with "--" before printing the ">" operator. If it does, I'll add a space.

**Comment by adam-azarchs** [comment]
It looks like #8252 tried to fix this, but it doesn't seem to actually work.  I haven't dug deep into why, but at least in my use case I'm using swc as the minifier in a webpack build, where pre-minification it's got `a.innerHTML="<script>\x3c/script>"` (which comes from [react-dom](https://github.com/facebook/react/blob/1d5667a1273386f84e416059af7b6aba069e068e/packages/react-dom-bindings/src/client/ReactFiberConfigDOM.js#L446), so I'd expect this to be a fairly common thing for people to encounter), so I'm wondering if maybe the issue is one of order of operations between converting `\x3c` to `/` and  escaping `/` to `\/`.
