### ISSUE TITLE
Swc fails to transpile optional chain operators in parentheses with an outer optional chain

### ISSUE THREAD

**Issue by natan-stripe** [swc-project/swc#7796]
### Describe the bug

It seems like, in certain cases involving parentheses, the transpiler is not properly removing the optional chain operator even though `es5` is the target. I've included a very small reproduction case for the issue.

### Input code

```typescript
// The type cast actually doesn't matter for reproducing the issue, but, I've included it to illustrate a realistic use case.
const foo = (a?.b as string)?.c;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "refresh": true
      }
    },
    "target": "es5",
  },
  "module": {
    "type": "commonjs",
    "ignoreDynamic": true,
    "strictMode": false
  },
  "isModule": true
 }
```

### Playground link

https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVdBItNdL0rTXS7YGAFJpoNwWAAAA&config=H4sIAAAAAAAAA1WPvQ6DMAyE9z4F8ty1S%2BcuHXgIKxgaRH5kG6kI8e5Nwk9hi7%2BzL3fzraqgFwPPak7PNERkIT7mRGTyit9EQKdIYthGhfuuqmRJeaQDNZNHZ83bxcC6iUVb1hVQRi9tYHf%2BhgmNnkBBLZN8zhbJ5GqF3FE%2BA5JHSVUUcKEZB%2FrXytHzlgnOBd%2FLVgBs5wPTa018KQKibI3WocmHLQ5Ch7uVevdfky23HyOpOp5KAQAA

### Expected behavior

The output should not include any syntax that is invalid for `es5`.

Expected output:
```
var _a_b, _a;
var foo = (_a = a) === null || _a === void 0 ? void 0 : (_a_b = _a.b) === null || _a_b === void 0 ? void 0 : _a_b.c;
```

### Actual behavior

The actual output still includes an optional chain operator.

Actual output:
```
var _this;
var foo = (_this = (a?.b)) === null || _this === void 0 ? void 0 : _this.c;
```

### Version

1.3.66

**Comment by jridgewell** [comment]
This was fixed with https://github.com/swc-project/swc/pull/7614, released as v1.3.68. Using a more recent version on the playground will [correctly transpile](https://play.swc.rs/?version=1.3.76&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVdBItNdL0rTXS7YGAFJpoNwWAAAA&config=H4sIAAAAAAAAA1WPvQ6DMAyE9z4F8ty1S%2BcuHXgIKxgaRH5kG6kI8e5Nwk9hi7%2BzL3fzraqgFwPPak7PNERkIT7mRGTyit9EQKdIYthGhfuuqmRJeaQDNZNHZ83bxcC6iUVb1hVQRi9tYHf%2BhgmNnkBBLZN8zhbJ5GqF3FE%2BA5JHSVUUcKEZB%2FrXytHzlgnOBd%2FLVgBs5wPTa018KQKibI3WocmHLQ5Ch7uVevdfky23HyOpOp5KAQAA)
