### ISSUE TITLE
GeneratorFunction constructor incorrect

### ISSUE THREAD

**Issue by hoivee** [swc-project/swc#7981]
### Describe the bug

After using SWC conversion, the constructor of the generator function is incorrect

### Input code

```typescript
function *generator() {
  yield fetch('/api/test1');
  yield fetch('/api/test1');
}

function isGenerator(obj) {
  const constructor = obj?.constructor;
  if (!constructor) {
    return false;
  }
  if (
    'GeneratorFunction' === constructor.name ||
        'GeneratorFunction' === constructor.displayName
  ) {
    return true;
  }
  return false;
}
console.log('isGenerator', isGenerator(generator));
```

### Playground link

https://play.swc.rs/?version=1.3.86&code=H4sIAAAAAAAAA41Ruw6CMBTdSfiH61QwBuJsiJtu%2FkMtt1hTW9KWgQj%2FbnmmsujS4bxzyxvFnNAK9hUqNNRpk6TwjiOAVqAsgaNjj4TktBa5Q%2BuOJD39Yvs4iiO%2BJAt7XaP1%2FTmnM62sm17TMM9BAZ49ZwE0FgkOyS4AZz%2BAQdcYBZxKi6OyX%2BQTT9bayzyFQFEUYWem6Auh6ybDv6ZS2FrS9ua9g3E7yMuCPZuVHhuitMRM6iohwXHI4etU63%2Bk6ekDF76NcKYBAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

The console should print 'true'.

### Version

1.3.86

**Comment by kdy1** [comment]
Closing as a wontfix because I already decided to use generator implementation of `tsc` because it's better then one of babel in some aspects (mainly bundle size). 
Actually, old versions of SWC had babel-like generator transform.


https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABAKgOYFMzoE4EMpzYAUAlIgN4CwAUIogJ4zoA2AJosOlBABZEDkAelwAHGIKjoAzlACM-EgG4adRi3adufIaPGSZ8pTQC+NGqEiwEiGFIDimHPkJE4AIwBWZKrUQQEMn4BUNgg0ISIALyI7h4A-AB0-mAyoeHYyr4wwIhEAITJqWEE2N4qdIjYXCDYSMC4zFLomXSmWTlE5XT8Dlh4JQBi4NDwYPxRkdGFIcWECWC4ALboiAA+q10V3b1Og8NWYxNTwWklCay2Isy49AByS+jlZb50VVA1SDPN5W2v1bUcBpNTJtQpwZjoBLMOCoAS2Hb9Qj8AA0NnsjkRxAwfWcpSUQA
