### ISSUE TITLE
Use of Reflect.construct() creates redundent objects when calling super constructor

### ISSUE THREAD

**Issue by rikumi** [swc-project/swc#7987]
### Describe the bug

When setting `loose: false`, `super()` calls will be replaced with temporary super functions created by `_create_super` in [this file](https://github.com/swc-project/swc/blob/main/packages/helpers/esm/_create_super.js). These super functions choose to use `Reflect.construct()` wherever possible.

The problem is, when the derived class is constructed by the `new` operator, the `this` object is already created by the `new` operator itself, which would quickly become redundent and be garbage-collected later, in favor of the one constructed by the `Reflect.construct()`.

When this operation is repeated many times, the garbage collection overhead can be huge and cause performance related issues.

### Playground link

https://play.swc.rs/?version=1.3.87&code=H4sIAAAAAAAAA0vOSSwuVnBUqObiquXiSgbznBRSK0pS81Ig4gpAkJyfV1xSVJpckl%2BkoQkVA4Hi0oJUoIg1WKAWaAIAm5sB%2FU8AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

`super()` calls should be replaced by the super class constructor calls, which is well tested by babel. **At least it shouldn't be interpreted into just constructing a new object.**

### Version

1.3.82

**Comment by Jack-Works** [comment]
This problem is impossible to solve.

- `this` is always created when a function get called with `new`
- `this` must be returned by the parent class
- `Reflect.construct` must be used to correctly extend `class {}`, native class (Map, Set, ...) or function that uses `new.target`

## `this` must be returned by the parent class

the ECMAScript specification requires the derived class to use `this` returned from the parent class. This is an example:

```js
const a = {}
function Base() {
    return a
}
class Child extends Base {}

print(new Child === new Child) // true
```

Since it's impossible to use the class created in the derived class, there must be a temp object created.

**Comment by jridgewell** [comment]
@Jack-Works is correct, this isn't solvable on our end.
