### ISSUE TITLE
swc discards the array deconstruction when setting browser compatibility to convert async to generator, causing problems.

### ISSUE THREAD

**Issue by linghaoSu** [swc-project/swc#8507]
### Describe the bug

swc discards the array deconstruction when setting browser compatibility to convert async to generator, causing problems.

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA21RS26DMBTcc4rZYaTUByCiSFWrbqqoi3YVsXDNI0UCm9ombYS4e8EQQpt4Y2neeD7PZd1o49DBUIEehdE1wmNL4TYI6MfPpFbW4aslc9qJmmwjJNk3GrAEwp6UBMupEG3ldjaNYZ0p1SFCco8uAJw5%2BRuzjiE7vvsWpZtev2rrWDTYnTm6Il7pAwsfnx7en%2B%2F%2BnnDNdFD2pfRBhvhs7wcA53wJhBT7bsaBSnxQFSMMNwt0FFVLa6jPEGOfbS5iQ2SuluYpr0XDmLK%2BIrsSVxP5yuEf3kcR0nQxyoZel1pOmAONtaZ%2B3EvwolT5YjzIeRRJkmCpe95OTlY608rbm53kb03Wfj5RDymc%2FASjaPWNI52M0YbNrKDf%2FgI5KHlESgIAAA%3D%3D&config=H4sIAAAAAAAAA1WOzQrCMBCE7z5FyLl4sFVQ0EuliG8R6lQraVJ2t9IivruJrX%2B37MxkvrnPlNJXLvVG3cMzHOgF5Iw9wLYgDoZQh2Q0W0MM%2BoSDItz%2FRYLEgxMTVS1DCy6pbkWP7mPqETKOK0%2FNb1XH2KOqHQpPuTXMRQ17ei8Y%2F8%2BmDt34U2fxnR1REQle6U8I7vaTMHSGxDpd1ITK92q3Vdk6UfmFfIN4LbNpqC494fgKp%2FN08VYDdaQ4oWHiPJ6zUdRnRAEAAA%3D%3D

### Expected behavior

keep deconstruction when transform async to generator

### Version

1.3.100

**Comment by chenjiahan** [comment]
Some more context in this issue: https://github.com/web-infra-dev/rsbuild/issues/1281

**Comment by magic-akari** [comment]
Fixed in #8401. Released in [v1.3.101](https://play.swc.rs/?version=1.3.101&code=H4sIAAAAAAAAA21RS26DMBTcc4rZYaTUByCiSFWrbqqoi3YVsXDNI0UCm9ombYS4e8EQQpt4Y2neeD7PZd1o49DBUIEehdE1wmNL4TYI6MfPpFbW4aslc9qJmmwjJNk3GrAEwp6UBMupEG3ldjaNYZ0p1SFCco8uAJw5%2BRuzjiE7vvsWpZtev2rrWDTYnTm6Il7pAwsfnx7en%2B%2F%2BnnDNdFD2pfRBhvhs7wcA53wJhBT7bsaBSnxQFSMMNwt0FFVLa6jPEGOfbS5iQ2SuluYpr0XDmLK%2BIrsSVxP5yuEf3kcR0nQxyoZel1pOmAONtaZ%2B3EvwolT5YjzIeRRJkmCpe95OTlY608rbm53kb03Wfj5RDymc%2FASjaPWNI52M0YbNrKDf%2FgI5KHlESgIAAA%3D%3D&config=H4sIAAAAAAAAA1WOzQrCMBCE7z5FyLl4sFVQ0EuliG8R6lQraVJ2t9IivruJrX%2B37MxkvrnPlNJXLvVG3cMzHOgF5Iw9wLYgDoZQh2Q0W0MM%2BoSDItz%2FRYLEgxMTVS1DCy6pbkWP7mPqETKOK0%2FNb1XH2KOqHQpPuTXMRQ17ei8Y%2F8%2BmDt34U2fxnR1REQle6U8I7vaTMHSGxDpd1ITK92q3Vdk6UfmFfIN4LbNpqC494fgKp%2FN08VYDdaQ4oWHiPJ6zUdRnRAEAAA%3D%3D)

**Comment by chenjiahan** [comment]
👍 Thanks!
