### ISSUE TITLE
tagged template literals have wrong `this` when compiling ESM to CommonJS

### ISSUE THREAD

**Issue by seansfkelley** [swc-project/swc#8553]
### Describe the bug

Tagged template calls like `` tag`foo` `` are incorrectly transformed into something like `` (0,tag)`foo` ``, but only when compiling from ESM to CommonJS. This changes the `this` of the invoked template literal function. This only seems to happen when compiling to CommonJS in the presence of `import`/`export` statements. ESM -> ESM and CommonJS -> CommonJS are unaffected.

Related: https://github.com/swc-project/swc/issues/6146, https://github.com/swc-project/swc/issues/1742, https://github.com/swc-project/swc/issues/5381.

### Input code

```typescript
import { tag } from 'somewhere';
tag`hello`;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "Chrome >= 50"
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKlGoVihJTFeoVUgrys9VUC%2FOz00tz0gtSlW35gKKJ2Sk5uTkJ1gDAHGjHa4sAAAA&config=H4sIAAAAAAAAA2WOOw7CMAyG954i8szAwoIECzOHiIJbUjUP2Skiqnp3krQpRSxW%2Foe%2FeGqEgJ4VnMWUnkl4SYy06eRwtEG%2BkwOojGRF2gc41LTnHLVyYCzWvCQwOMdYk9Uz2uo27tnKGU%2FI%2FFvMVWm7Af%2FJZYBxj7Gk69Eh%2BqwyzjjbM3yb9csND5rvdT3QuHhoXzuapA5DvgluT3IGxfUiTscCbeYPfKkHiDMBAAA%3D

### Expected behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _somewhere = require("somewhere");
_somewhere.tag`hello`;
```

### Actual behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _somewhere = require("somewhere");
(0, _somewhere.tag)`hello`;
```

### Version

1.3.100

**Comment by magic-akari** [comment]
This is intentional and correct. When converting from ESM to CJS, we try to maintain the semantics of ESM as much as possible.

Consider the following code:

```JavaScript
// lib.mjs
export function tag() {
	return typeof this;
}

// main.mjs
import { tag } from "./lib.mjs";

console.log("esm", tag`hello`);
```

When running `node main.mjs`, we will get the following output: `esm undefined`.
Now let's consider the following CJS code:

```JavaScript
// lib.cjs
"use strict";
exports.tag = function tag() {
	return typeof this;
};

// main.cjs
"use strict";
const lib = require("./lib.cjs");

console.log("cjs direct", lib.tag`hello`);
console.log("cjs indirect", (0, lib.tag)`hello`);
```

We will find that only the indirect call, `cjs indirect`, produces the same result as `esm`. This is because when directly calling the `tag` function, its `this` refers to the top-level `this`, which is `undefined`. In CJS, we convert it to `lib.tag` to correct the `this` binding, resulting in the use of `(0, lib.tag)` for indirect calls.
