### ISSUE TITLE
Compress - Wrong output

### ISSUE THREAD

**Issue by INeedJobToStartWork** [swc-project/swc#8587]
### Describe the bug

Compress does wrong transform code and giving other output than should

Tried on nightly and last update in browser

You can change `userManager` on "pnpm/8.14.0 npm/? node/v18.5.0 win32 x64" to see real output or just on "npm"/"pnpm" etc

### Input code

```typescript
type pkgManagerSupport = "npm" | "yarn" | "pnpm" | "bun";

const packageType = (() => {
	const userManager = process.env.npm_config_user_agent;

	const startWithSupport = (manager: pkgManagerSupport) => userManager?.startsWith(manager);
	if (userManager === void 0) return "npm";
	if (startWithSupport("pnpm")) return "pnpm";
	if (startWithSupport("yarn")) return "yarn";
	if (startWithSupport("bun")) return "bun";

	throw new Error("Unsupported package manager");
})();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.108-nightly-20240201.1&code=H4sIAAAAAAAAA32RP2%2FCMBDF50TKdzh5speIucjt1JGpRR0jE0yIEGfr7IBQy3fHfxJIW7Wb7fu9d3fP%2FmI12EO3Uqg6TW%2BDtYY8SGBojwy%2BgF0UYTrY6WUzIFtWZVW2Bp0Hq9pD0L5HJwmcC5DP8FmVRS4PTtPoHsqWTKudqzWe6uDXBGbXd02EmoCgT8aj1HlF%2FqP3%2B8dY%2FJitnn4PnfrOur3USe%2BiwSQTwb7od8C%2FTSUlnEy%2FhYUA0n4gzNtP7M8xeI5CPGj7P54inOHp%2Fjce853R97gLvydzBtRneCUyxNkaXRbp7fQNMG7K4qpXwcXyBmKn1D7jAQAA&config=H4sIAAAAAAAAA32UO5LbMAxA%2Bz2FR%2FW2SZEDpMsZODQJytxQhIYAvdbs%2BO6BKPmTNaROwsOP%2BH29HQ7dB7nu1%2BFLPuVntIWg3P9FQlNmexFJx9MI5EocuXu%2FUaYZBZsImui6kI5t6YFnK6Afq3qXEAlExqXCKhpijmF6judwGAsQPclEKu7qAJnpFu39mRX8pP%2F8NvkRMYHNO8RYMjEz9FA0xw5TsiOBOduieJkztSUSaiFmWBm8GQuOKs8%2BcsQsMV%2BpB%2BuNQw8KigUcxzNoZhJLzDLJ85T3NOzhWPu%2B9fibNZxtqpaVmHBpLZFsFa8njMQm1KyVcIEbNVjgWtzvljGYAlxLfrX7wJg3evIXQCqQLFG2A2h%2Bm0aQedqyDruWMQcZWZ4ULuOtvTJDL0U1MQalsnNloHDUulnAVwdzZZ2Wzoo3ykfRg4EQZFYU1%2FQZ2Z20oPOSY1CA9NcGbaoWYO5buMHnhdjBv%2BWVrA%2FYqjFYPm1TmoYjpp0AA%2FAJ%2FY6CtIJxGxe5Epdxm9fsQUYDvKpSqYHXIyALwGhSu5UvsyHrIR5Nn%2FD4OBOrwvV%2Bgweb%2B8e%2BL2f4bVXoBvS1wfXAz%2F1dzvLP7qF0u8L3xLtIf26WLej1HzaDscosBgAA

### SWC Info output

SWC Playground

### Expected behavior

output should be: "npm" | "pnpm" | "yarn" | "bun" | throw new Error("Unsupported package manager")

### Actual behavior

Output Boolean: `true` or `false`

### Version

1.3.108-nightly-20240201.1

### Additional context

I created IIFE function to check user user_manager and return it and not need to use () to call function.
After this i came on swc to check result of it.

**Comment by kdy1** [comment]
The return value is dropped because it's not used. If you use `packageType` , the result is preserved.

https://play.swc.rs/?version=1.3.108-nightly-20240201.1&code=H4sIAAAAAAAAA32RPU%2FDMBCG50TKfzh5speIucgwMXYC1DEyqZtGbc%2FW2WlVQf97%2FZG0AQSbP573vbv3%2FNlqsLtuqVB1ml4Haw15kMDQHhh8ATsrwnSw08vHgOyxKquyNeg8WNXugvYtOkngXIB8gs%2BqLPL34DSN7uHbkmm1c7XGYx38msBs%2Bq6JUBMQ9Ml4lDqvyK96v723xQ%2FZavG76VR3Vu25TnoXDSaZCPZFvwH%2BrSsp4Wj6NTwIIO0Hwjz9xP5sg%2BcoxJ22%2F%2BMpwhme7n%2FjMd8ZfYu78FsyJ0B9ghciQ5y9o8sivZ7WAOOkLI56EVzcNmX2ut6bjs%2F2Ja4449I5%2FwEAAA%3D%3D&config=H4sIAAAAAAAAA32UO5LbMAxA%2Bz2FR%2FW2SZEDpMsZODQJytxQhIYAvdbs%2BO6BKPmTNaROwsOP%2BH29HQ7dB7nu1%2BFLPuVntIWg3P9FQlNmexFJx9MI5EocuXu%2FUaYZBZsImui6kI5t6YFnK6Afq3qXEAlExqXCKhpijmF6judwGAsQPclEKu7qAJnpFu39mRX8pP%2F8NvkRMYHNO8RYMjEz9FA0xw5TsiOBOduieJkztSUSaiFmWBm8GQuOKs8%2BcsQsMV%2BpB%2BuNQw8KigUcxzNoZhJLzDLJ85T3NOzhWPu%2B9fibNZxtqpaVmHBpLZFsFa8njMQm1KyVcIEbNVjgWtzvljGYAlxLfrX7wJg3evIXQCqQLFG2A2h%2Bm0aQedqyDruWMQcZWZ4ULuOtvTJDL0U1MQalsnNloHDUulnAVwdzZZ2Wzoo3ykfRg4EQZFYU1%2FQZ2Z20oPOSY1CA9NcGbaoWYO5buMHnhdjBv%2BWVrA%2FYqjFYPm1TmoYjpp0AA%2FAJ%2FY6CtIJxGxe5Epdxm9fsQUYDvKpSqYHXIyALwGhSu5UvsyHrIR5Nn%2FD4OBOrwvV%2Bgweb%2B8e%2BL2f4bVXoBvS1wfXAz%2F1dzvLP7qF0u8L3xLtIf26WLej1HzaDscosBgAA
