### ISSUE TITLE
Minifier incorrectly renames identifiers

### ISSUE THREAD

**Issue by levi-nz** [swc-project/swc#8790]
### Describe the bug

The minifier incorrectly renames identifiers if the variable name is the same as the value's identifier, eg `var btoa = btoa;` becomes `var l = l;`

### Input code

```typescript
var btoa = btoa;

const text = btoa("Hello world");
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAytLLFJIKslPVLAFU9a8XLxcyfl5xSUKJakVJVBRDSWP1JycfIXy%2FKKcFCVNoCIAtAg4yzcAAAA%3D&config=H4sIAAAAAAAAA32QTQ6CMBCF95yCzNoFsjDGO3gGM6kDKba06RQiIdzd8lOESNy0nfe%2B6WRen6QpVCzglvbhGQqLjsmtdVC4qz2%2BgwIkNLJw0no4Rbfi0SpQMU3SMDvg0ZXkpy7OszxfOkAZwxQ7Fk3LWhbddqYw2jpi3oMjinWpaIOOo4xV1JIKqnfNygbnRWQfQiFzjZp%2BfotE8de1TrboKdzGHkGSrgcqY4FOnrNdOCGeJJ5TUKDNs9nsA76zNId2gS8U84nrgeR7bBy1ZPgAtz%2FrR8kBAAA%3D

### Expected behavior

The expected output should be something like:

```js
var l=btoa;const o=l("Hello world");
```

### Actual behavior

The variable's value becomes the variable's new name, causing incorrect behaviour

### Version

1.3.100

**Comment by Austaras** [comment]
This is the expected behavior and it aligns to terser.

In this situation, JS behavior can be divided into two categories
1. In es module and other environment where top level var can shadow anything, due to var hoist, the code should act like
```js
var a = undefined;

const text = a("Hello world");
```
2. In other environment where top level may not shadow global provided vars, the code should act like
```js
var a = undefined;

const text = btoa("Hello world");
```
However, there's no standardized list of what runtime may provide, so we only respect this behavior to a very limited common subset namely `undefined` and `NaN`.
