### ISSUE TITLE
Can SWC match TS emit for Parameter Properties?

### ISSUE THREAD

**Issue by robpalme** [swc-project/swc#9418]
Is there some config to get SWC to emit original authentic TS parameter properties?

---

I found that using TS parameter properties in SWC leads to JS emit that deviates from what TS produces and deviates from JS semantics.  Specifically, when this TS feature is detected in a given class, SWC relocates all field initializers for that class into the constructor body.

Please note this is not about older JS versions or older TS modes.  This is the behavior when **not** down-levelling and when ensuring `useDefineForClassFields: true` - which is enabled by default in TS when `target: es2022` or `target: esnext`.  So I'm asking about the most modern/minimal of output.

## TypeScript Compilation

With `tsc`, field initializers are **not** relocated.

<table><th>Source</th><th>TS emit</th><tbody><td>

```ts
class TypeScriptParameterProperties {

    initializedField = this.pp;
    constructor(public pp: any) {

        console.log('finally');
    }
}
```

</td><td>

```ts
class TypeScriptParameterProperties {
    pp;
    initializedField = this.pp;
    constructor(pp) {
        this.pp = pp;
        console.log("finally");
    }
}
```

</td></tbody></table>

[TS Playground link](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99#code/MYGwhgzhAEBSYDcwGVgCcCWAHALtA3gFDQnQD0Z0AAjhALQYDmAdgPZoCmxpGzGOGMCAwAvDgBMAYhg4hx0ALzQcACwwQAdGwAKWANzcSwVswg40AV2A52ACh1YAXNDDMAngEoCh0kZMRWEA4NEFZGWwAiADNeIRA3CI8DXwBfQjTQSBgAFTcsDlRMXG0wNDAAWw4cDjRtNFZ8tAEOGCJfCmpaBhZ2Ll9efkFhMSkZOUVlNU0sfR9jU3MrGzRbLAsAI2FgaBnnV09vX195gKCQsMiY5jiEpJ80tKA) [StackBlitz ilnk](https://stackblitz.com/edit/stackblitz-starters-hccu47?file=index.js&file=index.js&view=editor)

## SWC Compilation

With `swc`, field initializers are relocated into the constructor if (and only if) the class uses TS parameter properties.

<table><th>Source</th><th>SWC emit</th><tbody><td>

```ts
class TypeScriptParameterProperties {

    initializedField = this.pp;
    constructor(public pp: any) {


        console.log('finally');
    }
}
```

</td><td>

```ts
class TypeScriptParameterProperties {
    pp;
    initializedField;
    constructor(pp){
        this.pp = pp;
        this.initializedField = this.pp;
        console.log("finally");
    }
}
```

</td></tbody></table>

[SWC Playground link](https://play.swc.rs/?version=1.7.10&code=H4sIAAAAAAAAA5XOsQ6CQAwG4J2naJhgEHaNiZODE4m%2BQD0qNql3l14xQcO7q6CbCx3%2F%2FH%2FzOcGU4IB3PDrlaPDM4H11DTtLK%2B58UJoS9myMwg9q90zSwhbsyqnyoYmbqeGCT6a9s6DFJ10D%2BqH8PvwVglAloSvyC3sUGfJyHo%2FZmLnJchoizZYGFW9kpI2GSGpMaTEv%2FsHF%2FizsIC4XvgCxMVd3LgEAAA%3D%3D&config=H4sIAAAAAAAAA2VPOw7DIAzdcwrkuUPF0KF36CEQdSIifsKOVBTl7gUS0lZdLPt9%2FOx1EAJm0nAXa2nLEFUiTOdcEMqe1asgwDki6WQiw6WzTJUalSVs0LYzwCpNyNWFJK9SHg6wIRB2x4E5482YvzN1cDEh0a%2BwSpWfLP4ntgIuPJfGHs%2FUg%2FcTbvAR9bRzMxh6dCenBYftDc60PAQYAQAA)

## Conclusion

Based on [history from @magic-akari ](https://github.com/swc-project/swc/pull/7055#issuecomment-1464897834) it looks like this is intentional to have Swc-specific behavior.  Which is Swc's choice to make - there is no spec or compliance test suite for this TS-specific feature.

For projects that want to preserve JS semantics and also want to match the official TypeScript output (e.g. in Node's experimental TS support), is there a way to do so?  If not, then please consider this to be a polite feature request for a new mode, e.g. `"jsc.transform.noInitializerRelocation"`

**Comment by magic-akari** [comment]
I believe it's a TypeScript bug. 
I meant to report it sooner but kept forgetting. Here's the issue link.

- https://github.com/microsoft/TypeScript/issues/59589

**Comment by robpalme** [comment]
Thanks for the prompt and thorough explanation, @magic-akari 🙏 Raising this now with the TS team is a good way to get clarity on the stability of the transforms.

I think you describe the situation perfectly.  The choice here is either consistency across ES down-level targets, or consistency between TS and JS.  Today SWC favors the former and TS favors the latter.

Would you be happy accepting a PR to SWC to introduce a `"jsc.transform.noInitializerRelocation"` option now, or would you prefer to wait for a decision from TypeScript team on https://github.com/microsoft/TypeScript/issues/59589?

**Comment by marco-ippolito** [comment]
is there any chance we can get swc behave like TSC with an option in `transformSync`? When the bug is fixed by ts we flip it

**Comment by magic-akari** [comment]
I want to make one thing clear: I'm not advocating for TypeScript to alter its transform emit to align with SWC. I hope TS will resolve its own consistency problems. 

Like Babel, SWC maintains consistency, but TypeScript's output is different between ES2020 and ESNEXT.

I'm convinced that these two outputs can't both be correct.

Babel has chosen an output order that more closely aligns with JavaScript semantics by omitting the `public` keyword, similar to TypeScript's esnext output. Conversely, SWC has selected an output style that aligns with TypeScript's ES2020 output.

Nevertheless, Babel also faces user-reported issues, as seen here: https://github.com/babel/babel/issues/13779

I genuinely hope that TSC, Babel, and SWC can achieve consistent output.

Several potential solutions exist for this issue:

1. The TypeScript team chooses a standard for output and improves consistency.
2. The TypeScript team prioritizes stability over consistency and decides against making any changes.

If it's the first option, SWC and Babel simply need to conform to TypeScript's decision and adjust accordingly.
If it's the second, SWC will have to emulate the varying outputs of TypeScript's at different targets.

Furthermore, I believe that it is more fitting to address this issue through the TypeScript team's decision rather than adding options on our own.

**Comment by robpalme** [comment]
Thanks for clarifying, @magic-akari. Apologies if I my summary was off. I updated my [other comment](https://github.com/nodejs/node/pull/54283#issuecomment-2282778671) to be more precise.
